- matgl/apps/pes.py
- matgl/utils/training.py
Similar to #125 in the `PotentialLightningModule`
* added an explicit `calc_site_wise` kwarg in `Potential` to match other predictions.
* the returned dictionary now has more entries, I don't think that should break backwards compat but let me know.
* calculation of site-wise is inferred based on whether site_wise_weight is passed. The same could be done for stress.
Please let me know any suggestions
> Adapt potential lightning module to include optional site wise

- matgl/apps/pes.py
- matgl/utils/training.py
My understanding from their docs is that pytorch lightning recommends using `register_buffer` for tensors that are model attributes that are not optimized, and that calls of `to(device)` should be avoided since the lightning module "knows what device it is on".
I have checked that using register_buffer works for training on GPU successfully, but I am not an expert on this so please have a look.
https://lightning.ai/docs/pytorch/stable/accelerators/accelerator_prepare.html
> use register buffer in Potential in LightningPotential and PES

- matgl/ext/ase.py
> Add some missing type hints to `Relaxer.relax`

- matgl/graph/converters.py
- tests/graph/test_compute.py
I set `edata["pbc_offshift"]` and `ndata["pos"]` as float64 to correctly handle creating line graphs when some bond lengths are right at the cutoff.
I added a test for this edge case with a made-up structure.
> set pbc_offsift and pos as float64

- matgl/layers/_atom_ref.py
- matgl/utils/io.py
- tests/layers/test_atom_ref.py
A few edits to the `AtomRef` class:
* added `max_z` as optional kwarg for cases where offsets have not been fitted yet.
* Removed all use of `numpy`
* Use `lstsq` instead of explicitly pseudo-inverse
* Made `property_offset` a buffer to avoid errors when running on GPU and with lightning modules
* Save precomputed identity matrix for onehot vectors as buffer.
> AtomRef Updates

- matgl/layers/_atom_ref.py
- matgl/layers/_core.py
- matgl/layers/_readout.py
> Sequence instead of list for inputs

- matgl/layers/_atom_ref.py
- matgl/utils/training.py
- tests/utils/test_training.py
* choose distribution and gain
```sh
```
> Allow to choose distribution in xavier_init

- docs/tutorials/Training a M3GNet Potential with PyTorch Lightning.md
- examples/Training a M3GNet Potential with PyTorch Lightning.ipynb
> add testing to m3gnet potential training example

- dev/refactor.py
- pretrained_models/M3GNet-MP-2021.2.8-DIRECT-PES/model.json
- pretrained_models/M3GNet-MP-2021.2.8-PES/model.json
- src/matgl/apps/pes.py
- tests/apps/test_pes.py
- tests/conftest.py
- tests/data/test_transformer.py
- tests/ext/test_ase.py
- tests/ext/test_pymatgen.py
- tests/graph/test_compute.py
- tests/graph/test_data.py
- tests/layers/test_activations.py
- tests/layers/test_atom_ref.py
- tests/layers/test_basis.py
- tests/layers/test_bond.py
- tests/layers/test_core_and_embedding.py
- tests/layers/test_graph_conv.py
- tests/layers/test_readout.py
- tests/layers/test_three_body.py
- tests/models/test_m3gnet.py
- tests/models/test_megnet.py
- tests/models/test_wrapper.py
- tests/test_integration.py
- tests/utils/test_cutoff.py
- tests/utils/test_io.py
- tests/utils/test_maths.py
- tests/utils/test_training.py
The model version of the Potential class is changed from 1 to 2. This prevents the wrong loading of the model.
```sh
```
> model version for Potential class is modified

- src/matgl/apps/pes.py
Currently,
```
from pymatgen.util.testing import PymatgenTest
import matgl
from matgl.ext.ase import M3GNetCalculator
def LiFePO4():
return PymatgenTest.get_structure("LiFePO4")
potential_m3gnet = matgl.load_model("M3GNet-MP-2021.2.8-PES")
m3gnet = M3GNetCalculator(potential=potential_m3gnet, stress_weight=1.)
print(m3gnet.get_stress(atoms = LiFePO4().apply_strain(0.1).to_ase_atoms()))
```
gives
```
array([[-2.4297804e+01,  2.0667364e-01, -1.2357983e-04],
[ 2.0667414e-01, -2.3150066e+01,  4.2587479e-05],
[-1.2232375e-04,  4.3453932e-05, -2.6601597e+01]], dtype=float32)
```
, which is incorrect (stress should be positive for a positive strain). This seems to be because, when calculating the stresses, volume is calculated as `volume = torch.det(lattice)`, but for the structure above, this …
> Ensure volume is positive in stress calculation

- src/matgl/ext/ase.py
- tests/ext/test_ase.py
Closes #202 (see issue report for additional details).
Summary: I corrected the type for the `energy` property in the ASE calculator interface, such as when doing `atoms.get_potential_energy()` or fetching the property directly from `atoms.calc.results["energy"]`. The ASE standard is that it is type `float`, but it is an `NDArray` of length 1 in `main`.
> Ensure the `energy` property is type `float` in ASE calculator

- src/matgl/apps/pes.py
- src/matgl/graph/compute.py
- src/matgl/graph/data.py
- src/matgl/layers/_basis.py
- src/matgl/layers/_three_body.py
- src/matgl/utils/maths.py
This PR adds necessary [tensor.to()](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html) calls to properly set up new tensors created during training. This is [recommended](https://lightning.ai/docs/pytorch/stable/accelerators/accelerator_prepare.html#init-tensors-using-tensor-to-and-register-buffer) by PyTorch Lightning so that training models can be done in a hardware-agnostic manner and scale to an arbitrary number of devices without changing any other code. 
Adding these changes removes the need for using `torch.set_default_device("cuda")` and setting default generator for dataloaders `generator=torch.Generator(device='cuda')`. Additionally, these updates ensure `num_workers>0` may be used during training, which has been seen in other issues, such as #213, and …
> Adding Tensor Placement Calls For Ease of Training with PyTorch Lightning

- src/matgl/models/_m3gnet.py
- tests/models/test_m3gnet.py
In this PR, the `forward` method of M3GNet is modified so that intermediate outputs in "embedding", "gc_1", "gc_2", "gc_3", and "readout" layers can be extracted, while the "final" layer output stays as the default output. This allows the usage of M3GNet intermediate outputs as atom, bond, and structure features. Documentations and tests are provided.
Major changes:
1. Added the argument of `output_layer` into the `forward` method.
2. Added comprehensive tests for the `predict_structure` method.
3. Added the argument of `output_layer` into the `predict_structure` method.
4. Edited the variable names in the readout layer of M3GNet to be more precise. For example, the `node_vec` is renamed to `field_vec`, as this variable can either be node feature or edge feature instead of just node …
> Add output_layer argument to M3GNet forward method to return intermediate layer outputs

- src/matgl/__init__.py
- src/matgl/apps/pes.py
- src/matgl/graph/compute.py
- src/matgl/layers/_graph_convolution.py
- tests/test_default_dtype.py
Due to the large memory consumption for M3GNet using torch.float32, we offer torch.float16 option to reduce memory usage by removing unnecessary float() (torch.float32) in the M3GNet implementation. It should be noted that only cuda version is available for this option because the operation addmm_impl_cpu_ is not implemented for torch.float16. When the user defines the default data type as torch.float32 with cpu, the exception will raise "Exception: torch.float16 is not supported for M3GNet because addmm_impl_cpu_ is not implemented for this floating precision, please use size = 32, 64 or using 'cuda' instead !!".
- [ x] Google format doc strings added. Check with `ruff`.
- [ x] Type annotations included. Check with `mypy`.
- [ x] Tests added for new features/fixes.
- [ x] If applicable, …
> remove unnecessary float() for offering torch.float16 option

- src/matgl/ext/ase.py
This is a follow-up to #203.
The `Calculator.results` dictionary from an M3GNet run yields something like `'free_energy': array(-4.0938973, dtype=float32)` for the free energy property. This causes some havoc in places (e.g. monty jsanitization) since the array isn't iterable. It doesn't have a defined `len` without the brackets. We should really make this a `float` instead anyway. That's what I do in this PR.
> Ensure `free_energy` property is `float`

- src/matgl/ext/ase.py
The `PESCalculator.results["free_energy"]` property should be formatted as a `float` but is currently formatted as a `np.array(float)`. For instance, `array(-4.0938973, dtype=float32)`. Since this is not the expected ASE type and because it is not iterable, this can cause a variety of unexpected problems. https://github.com/materialsvirtuallab/monty/issues/668 is just one example.
I have ensured the `free_energy` property is returned as a `float` in this PR.
> Ensure `free_energy` property is a `float` and not `np.array(float)`

- src/matgl/layers/_atom_ref.py
Change the fitting method of AtomRef from `torch.linalg.lstsq` to `np.linalg.pinv` mthod
```python
for i in range(3):
training_set, validation_set, test_set = split_dataset(
dataset, 
frac_list=[0.9, 0.05, 0.05], 
random_state=42, 
shuffle=True
)
train_graphs = []
energies = []
forces = []
for (g, lat, l_g, attrs, lbs) in training_set:
train_graphs.append(g)
energies.append(lbs["energies"])
forces.append(lbs['forces'])
element_refs = AtomRef(torch.zeros(89))
element_refs.fit(train_graphs, torch.hstack(energies))
print(element_refs.property_offset)
```
The output for the above block gives:
```text
tensor([ -3.3743,  -0.3157,  -2.5775,  -3.6737,  -7.1368,  -8.9913,  -8.6316,
-8.3601,  -6.4603,   0.0000,  -3.3769,  -4.0194,  -6.7818,  -8.5984,
-9.2705,  -8.9952,  -7.0834,   0.0000,  -5.5053, …
```
> Move AtomRef Fitting to numpy to avoid bug

- README.md
matgl depends on torch==2.2.1 in requirements.txt
> Matgl depends on torch==2.2.1

- pyproject.toml
- tests/models/test_tensornet.py
A unit test is added for testing SO(3) equivariance to improve the coverage.
```sh
```
> Improve the TensorNet model class coverage

- src/matgl/utils/training.py
- tests/utils/test_training.py
This PR allows loss function calculation in MGLDataset.
Now we're able to train with the dataset of partial labels.
The default behavior of the training and loss function is `allow_missing_labels: bool = False`
So this PR does not influence the performance of previous working codes.
Major changes:
- `src/matgl/utils/training.py`
- `tests/utils/test_training.py`
Example:
```
energies[2] = np.nan
forces[4] = (np.nan * np.ones((len(structures[4]), 3))).tolist()
stresses[6] = (np.nan * np.ones((3, 3))).tolist()
magmoms[8] = (np.nan * np.ones((len(structures[8]), 1))).tolist()
dataset = MGLDataset(
structures=structures,
converter=converter,
labels={
"energies": energies,
"forces": forces,
"stresses": stresses,
"magmoms": magmoms,
},
)
```
The above dataset with some missing labels should be …
> Allow missing label in MGLDataset

- src/matgl/models/_m3gnet.py
The constructor simply passes the value down to the underlying M3GNetBlock layers. The default value is None (corresponding to no dropout), the same as for the M3GNetBlock layers - so there is no change to default behaviour. I'm using this to regularize my models - and it's working as intended.
Changes:
- feature 1: Added a parameter to the constructor of a M3GNet model that allows passing down a dropout value. The default value preserves current behaviour.
- (N/A) Tests added for new features/fixes .
- (N/A) If applicable, new classes/functions/modules have [`duecredit`](https://github.com/duecredit/duecredit) `@due.dcite` decorators to reference relevant papers by DOI ([example](https://github.com/materialsproject/pymatgen/blob/91dbe6ee9ed01d781a9388bf147648e20c6d58e0/pymatgen/core/latti …
> Added a dropout argument to the M3GNET constructor

- src/matgl/ext/ase.py
Closes https://github.com/materialsvirtuallab/matgl/issues/638 to prevent bug with next ASE release.
> Remove deprecated `ExpCellFilter`
